Creator: Dhanajit Brahma

Adapted from the original implementation in tensorflow from here: https://github.com/jsyoon0823/GAIN

Generative Adversarial Imputation Networks (GAIN) Implementation on Letter and Spam Dataset

Reference: J. Yoon, J. Jordon, M. van der Schaar, "GAIN: Missing Data Imputation using Generative Adversarial Nets," ICML, 2018.

In [1]:
#%% Packages
import torch
import numpy as np
from tqdm import tqdm
import torch.nn.functional as F

In [2]:
dataset_file = 'Spam.csv'  # 'Letter.csv' for Letter dataset an 'Spam.csv' for Spam dataset
use_gpu = False  # set it to True to use GPU and False to use CPU

In [3]:
torch.cuda.set_device(0)

In [4]:
#%% System Parameters
# 1. Mini batch size
mb_size = 128
# 2. Missing rate
p_miss = 0.2
# 3. Hint rate
p_hint = 0.9
# 4. Loss Hyperparameters
alpha = 10
# 5. Train Rate
train_rate = 0.8

#%% Data

# Data generation
Data = np.loadtxt(dataset_file, delimiter=",",skiprows=1)

# Parameters
No = len(Data)
Dim = len(Data[0,:])

# Hidden state dimensions
H_Dim1 = Dim
H_Dim2 = Dim

# Normalization (0 to 1)
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)    

#%% Missing introducing
p_miss_vec = p_miss * np.ones((Dim,1)) 
   
Missing = np.zeros((No,Dim))

for i in range(Dim):
    A = np.random.uniform(0., 1., size = [len(Data),])
    B = A > p_miss_vec[i]
    Missing[:,i] = 1.*B

    
#%% Train Test Division    
   
idx = np.random.permutation(No)

Train_No = int(No * train_rate)
Test_No = No - Train_No
    
# Train / Test Features
trainX = Data[idx[:Train_No],:]
testX = Data[idx[Train_No:],:]

# Train / Test Missing Indicators
trainM = Missing[idx[:Train_No],:]
testM = Missing[idx[Train_No:],:]

#%% Necessary Functions

# 1. Xavier Initialization Definition
# def xavier_init(size):
#     in_dim = size[0]
#     xavier_stddev = 1. / tf.sqrt(in_dim / 2.)
#     return tf.random_normal(shape = size, stddev = xavier_stddev)
def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)
    
# Hint Vector Generation
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C
   

### GAIN Architecture   
GAIN Consists of 3 Components
- Generator
- Discriminator
- Hint Mechanism

In [5]:
#%% 1. Discriminator
if use_gpu is True:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       # Output is multi-variate
else:
    D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Hint as inputs
    D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # Output is multi-variate

theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

#%% 2. Generator
if use_gpu is True:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
else:
    G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # Data + Mask as inputs (Random Noises are in Missing Components)
    G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

    G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
    G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

    G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
    G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]

## GAIN Functions

In [6]:
#%% 1. Generator
def generator(new_x,m):
    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # Mask + Data Concatenate
    G_h1 = F.relu(torch.matmul(inputs, G_W1) + G_b1)
    G_h2 = F.relu(torch.matmul(G_h1, G_W2) + G_b2)   
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    
    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):
    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # Hint + Data Concatenate
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)  
    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] Probability Output
    
    return D_prob

#%% 3. Other functions
# Random sample generator for Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])        

# Mini-batch generation
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx

## GAIN Losses

In [7]:
def discriminator_loss(M, New_X, H):
    # Generator
    G_sample = generator(New_X,M)
    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8))
    return D_loss

def generator_loss(X, M, New_X, H):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    # Combine with original data
    Hat_New_X = New_X * M + G_sample * (1-M)

    # Discriminator
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8))
    MSE_train_loss = torch.mean((M * New_X - M * G_sample)**2) / torch.mean(M)

    G_loss = G_loss1 + alpha * MSE_train_loss 

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return G_loss, MSE_train_loss, MSE_test_loss
    
def test_loss(X, M, New_X):
    #%% Structure
    # Generator
    G_sample = generator(New_X,M)

    #%% MSE Performance metric
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2) / torch.mean(1-M)
    return MSE_test_loss, G_sample

## Optimizers

In [8]:
optimizer_D = torch.optim.Adam(params=theta_D)
optimizer_G = torch.optim.Adam(params=theta_G)

## Training

In [9]:
#%% Start Iterations
for it in tqdm(range(5000)):    
    
    #%% Inputs
    mb_idx = sample_idx(Train_No, mb_size)
    X_mb = trainX[mb_idx,:]  
    
    Z_mb = sample_Z(mb_size, Dim) 
    M_mb = trainM[mb_idx,:]  
    H_mb1 = sample_M(mb_size, Dim, 1-p_hint)
    H_mb = M_mb * H_mb1
    
    New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce
    
    if use_gpu is True:
        X_mb = torch.tensor(X_mb, device="cuda")
        M_mb = torch.tensor(M_mb, device="cuda")
        H_mb = torch.tensor(H_mb, device="cuda")
        New_X_mb = torch.tensor(New_X_mb, device="cuda")
    else:
        X_mb = torch.tensor(X_mb)
        M_mb = torch.tensor(M_mb)
        H_mb = torch.tensor(H_mb)
        New_X_mb = torch.tensor(New_X_mb)
    
    optimizer_D.zero_grad()
    D_loss_curr = discriminator_loss(M=M_mb, New_X=New_X_mb, H=H_mb)
    D_loss_curr.backward()
    optimizer_D.step()
    
    optimizer_G.zero_grad()
    G_loss_curr, MSE_train_loss_curr, MSE_test_loss_curr = generator_loss(X=X_mb, M=M_mb, New_X=New_X_mb, H=H_mb)
    G_loss_curr.backward()
    optimizer_G.step()    
        
    #%% Intermediate Losses
    if it % 100 == 0:
        print('Iter: {}'.format(it))
        print('Train_loss: {:.4}'.format(np.sqrt(MSE_train_loss_curr.item())))
        print('Test_loss: {:.4}'.format(np.sqrt(MSE_test_loss_curr.item())))
        print()

  0%|          | 20/5000 [00:00<00:54, 91.82it/s]

Iter: 0
Train_loss: 0.5152
Test_loss: 0.5198



  2%|▏         | 114/5000 [00:01<00:52, 92.71it/s]

Iter: 100
Train_loss: 0.06806
Test_loss: 0.06559



  4%|▍         | 216/5000 [00:02<00:45, 104.12it/s]

Iter: 200
Train_loss: 0.05994
Test_loss: 0.06531



  6%|▋         | 320/5000 [00:03<00:44, 104.51it/s]

Iter: 300
Train_loss: 0.05978
Test_loss: 0.06767



  8%|▊         | 421/5000 [00:04<00:42, 108.66it/s]

Iter: 400
Train_loss: 0.06446
Test_loss: 0.05426



 10%|█         | 523/5000 [00:04<00:40, 109.60it/s]

Iter: 500
Train_loss: 0.05409
Test_loss: 0.05788



 12%|█▏        | 622/5000 [00:05<00:40, 107.66it/s]

Iter: 600
Train_loss: 0.0585
Test_loss: 0.05803



 14%|█▍        | 722/5000 [00:06<00:40, 106.84it/s]

Iter: 700
Train_loss: 0.05506
Test_loss: 0.05192



 16%|█▋        | 821/5000 [00:07<00:40, 102.97it/s]

Iter: 800
Train_loss: 0.04246
Test_loss: 0.04355



 18%|█▊        | 920/5000 [00:08<00:39, 102.13it/s]

Iter: 900
Train_loss: 0.04913
Test_loss: 0.06069



 20%|██        | 1019/5000 [00:09<00:39, 102.01it/s]

Iter: 1000
Train_loss: 0.05207
Test_loss: 0.03956



 22%|██▏       | 1118/5000 [00:10<00:37, 102.23it/s]

Iter: 1100
Train_loss: 0.04474
Test_loss: 0.04724



 24%|██▍       | 1217/5000 [00:11<00:37, 100.88it/s]

Iter: 1200
Train_loss: 0.03953
Test_loss: 0.04841



 26%|██▋       | 1316/5000 [00:12<00:37, 97.29it/s] 

Iter: 1300
Train_loss: 0.04374
Test_loss: 0.07064



 28%|██▊       | 1417/5000 [00:13<00:33, 108.21it/s]

Iter: 1400
Train_loss: 0.03885
Test_loss: 0.05122



 30%|███       | 1518/5000 [00:14<00:32, 107.32it/s]

Iter: 1500
Train_loss: 0.04397
Test_loss: 0.03933



 32%|███▏      | 1618/5000 [00:15<00:31, 108.20it/s]

Iter: 1600
Train_loss: 0.03994
Test_loss: 0.06131



 34%|███▍      | 1718/5000 [00:16<00:30, 107.03it/s]

Iter: 1700
Train_loss: 0.03736
Test_loss: 0.04737



 36%|███▋      | 1815/5000 [00:17<00:32, 98.15it/s] 

Iter: 1800
Train_loss: 0.0371
Test_loss: 0.05934



 38%|███▊      | 1918/5000 [00:18<00:29, 105.98it/s]

Iter: 1900
Train_loss: 0.03637
Test_loss: 0.05514



 40%|████      | 2020/5000 [00:19<00:29, 101.88it/s]

Iter: 2000
Train_loss: 0.03389
Test_loss: 0.04854



 42%|████▏     | 2119/5000 [00:20<00:28, 102.41it/s]

Iter: 2100
Train_loss: 0.03272
Test_loss: 0.04731



 44%|████▍     | 2218/5000 [00:21<00:26, 103.35it/s]

Iter: 2200
Train_loss: 0.03435
Test_loss: 0.05516



 46%|████▋     | 2318/5000 [00:22<00:25, 104.68it/s]

Iter: 2300
Train_loss: 0.0316
Test_loss: 0.0675



 48%|████▊     | 2416/5000 [00:23<00:21, 119.60it/s]

Iter: 2400
Train_loss: 0.02686
Test_loss: 0.04957



 50%|█████     | 2519/5000 [00:24<00:23, 104.00it/s]

Iter: 2500
Train_loss: 0.03004
Test_loss: 0.0552



 52%|█████▏    | 2616/5000 [00:24<00:20, 118.40it/s]

Iter: 2600
Train_loss: 0.03073
Test_loss: 0.05001



 54%|█████▍    | 2720/5000 [00:25<00:21, 106.31it/s]

Iter: 2700
Train_loss: 0.03565
Test_loss: 0.059



 56%|█████▋    | 2821/5000 [00:26<00:20, 107.84it/s]

Iter: 2800
Train_loss: 0.02833
Test_loss: 0.06659



 58%|█████▊    | 2922/5000 [00:27<00:19, 106.29it/s]

Iter: 2900
Train_loss: 0.02753
Test_loss: 0.06168



 60%|██████    | 3021/5000 [00:28<00:19, 103.65it/s]

Iter: 3000
Train_loss: 0.03421
Test_loss: 0.04901



 62%|██████▏   | 3120/5000 [00:29<00:18, 103.90it/s]

Iter: 3100
Train_loss: 0.02746
Test_loss: 0.0503



 64%|██████▍   | 3216/5000 [00:30<00:18, 97.65it/s] 

Iter: 3200
Train_loss: 0.02908
Test_loss: 0.05465



 66%|██████▋   | 3317/5000 [00:31<00:15, 108.80it/s]

Iter: 3300
Train_loss: 0.02619
Test_loss: 0.04389



 68%|██████▊   | 3421/5000 [00:32<00:15, 103.76it/s]

Iter: 3400
Train_loss: 0.02324
Test_loss: 0.04538



 70%|███████   | 3517/5000 [00:33<00:16, 90.92it/s] 

Iter: 3500
Train_loss: 0.02695
Test_loss: 0.04522



 72%|███████▏  | 3618/5000 [00:34<00:14, 95.14it/s]

Iter: 3600
Train_loss: 0.02376
Test_loss: 0.05515



 74%|███████▍  | 3720/5000 [00:35<00:13, 96.70it/s]

Iter: 3700
Train_loss: 0.02336
Test_loss: 0.0466



 76%|███████▋  | 3816/5000 [00:36<00:11, 105.01it/s]

Iter: 3800
Train_loss: 0.02443
Test_loss: 0.04909



 78%|███████▊  | 3917/5000 [00:37<00:11, 97.57it/s] 

Iter: 3900
Train_loss: 0.02899
Test_loss: 0.05131



 80%|████████  | 4015/5000 [00:38<00:09, 102.99it/s]

Iter: 4000
Train_loss: 0.02319
Test_loss: 0.0531



 82%|████████▏ | 4113/5000 [00:39<00:09, 92.48it/s] 

Iter: 4100
Train_loss: 0.02269
Test_loss: 0.04696



 84%|████████▍ | 4217/5000 [00:40<00:07, 102.68it/s]

Iter: 4200
Train_loss: 0.02406
Test_loss: 0.04652



 86%|████████▋ | 4316/5000 [00:41<00:06, 106.87it/s]

Iter: 4300
Train_loss: 0.02592
Test_loss: 0.04874



 88%|████████▊ | 4415/5000 [00:42<00:05, 105.47it/s]

Iter: 4400
Train_loss: 0.02263
Test_loss: 0.06811



 90%|█████████ | 4515/5000 [00:43<00:04, 104.07it/s]

Iter: 4500
Train_loss: 0.02299
Test_loss: 0.0543



 92%|█████████▏| 4614/5000 [00:44<00:03, 104.88it/s]

Iter: 4600
Train_loss: 0.02236
Test_loss: 0.05448



 94%|█████████▍| 4713/5000 [00:45<00:02, 102.85it/s]

Iter: 4700
Train_loss: 0.0212
Test_loss: 0.05128



 96%|█████████▋| 4813/5000 [00:46<00:01, 103.92it/s]

Iter: 4800
Train_loss: 0.02093
Test_loss: 0.05248



 98%|█████████▊| 4917/5000 [00:47<00:00, 112.09it/s]

Iter: 4900
Train_loss: 0.02084
Test_loss: 0.06615



100%|██████████| 5000/5000 [00:48<00:00, 103.81it/s]


## Testing

In [10]:
Z_mb = sample_Z(Test_No, Dim) 
M_mb = testM
X_mb = testX
        
New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

if use_gpu is True:
    X_mb = torch.tensor(X_mb, device='cuda')
    M_mb = torch.tensor(M_mb, device='cuda')
    New_X_mb = torch.tensor(New_X_mb, device='cuda')
else:
    X_mb = torch.tensor(X_mb)
    M_mb = torch.tensor(M_mb)
    New_X_mb = torch.tensor(New_X_mb)
    
MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)
        
print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))

Final Test RMSE: 0.05813553261825125


In [11]:
imputed_data = M_mb * X_mb + (1-M_mb) * Sample
print("Imputed test data:")
# np.set_printoptions(formaM_mbtter={'float': lambda x: "{0:0.8f}".format(x)})

if use_gpu is True:
    print(imputed_data.cpu().detach().numpy())
else:
    print(imputed_data.detach().numpy())

Imputed test data:
[[0.02966124 0.         0.00875654 ... 0.00109215 0.00110132 0.00814394]
 [0.01613188 0.         0.01601679 ... 0.00023877 0.00792814 0.00145202]
 [0.         0.01800503 0.         ... 0.00331548 0.0030036  0.00669192]
 ...
 [0.         0.00511257 0.03400632 ... 0.00113482 0.00819355 0.00902778]
 [0.01511798 0.         0.         ... 0.         0.         0.00044192]
 [0.01387648 0.0502752  0.00813581 ... 0.01377253 0.02620011 0.00637626]]
